export interface Product {
  id: number
  name: string
  description: string
  price: number
  originalPrice?: number
  image: string
  brand: string
  category: string
  rating: number
  reviews: number
  sizes: string[]
  colors: string[]
  inStock: boolean
}

export const brands = ["Nike", "Adidas", "Puma", "Under Armour", "New Balance", "Reebok", "Jordan", "Converse"]

export const categories = [
  "أحذية رياضية",
  "تيشرتات",
  "شورتات",
  "بناطيل رياضية",
  "جاكيتات",
  "حقائب رياضية",
  "إكسسوارات",
  "معدات رياضية",
]

export const sampleProducts: Product[] = [
  {
    id: 1,
    name: "حذاء Nike Air Max 270",
    description: "حذاء رياضي مريح مع تقنية Air Max للراحة القصوى",
    price: 450,
    originalPrice: 550,
    image: "/nike-air-max-270.png",
    brand: "Nike",
    category: "أحذية رياضية",
    rating: 4.8,
    reviews: 124,
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["أسود", "أبيض", "أزرق"],
    inStock: true,
  },
  {
    id: 2,
    name: "تيشرت Adidas Originals",
    description: "تيشرت قطني مريح بتصميم كلاسيكي من أديداس",
    price: 120,
    originalPrice: 150,
    image: "/adidas-originals-tee.png",
    brand: "Adidas",
    category: "تيشرتات",
    rating: 4.6,
    reviews: 89,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["أسود", "أبيض", "رمادي"],
    inStock: true,
  },
  {
    id: 3,
    name: "حذاء Puma RS-X",
    description: "حذاء رياضي عصري بتصميم جريء وألوان زاهية",
    price: 380,
    image: "/colorful-puma-rs-x.png",
    brand: "Puma",
    category: "أحذية رياضية",
    rating: 4.5,
    reviews: 67,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["متعدد الألوان", "أسود", "أبيض"],
    inStock: true,
  },
  {
    id: 4,
    name: "شورت Under Armour",
    description: "شورت رياضي بتقنية Dri-FIT لامتصاص العرق",
    price: 95,
    originalPrice: 120,
    image: "/placeholder-vhen2.png",
    brand: "Under Armour",
    category: "شورتات",
    rating: 4.7,
    reviews: 156,
    sizes: ["S", "M", "L", "XL"],
    colors: ["أسود", "رمادي", "أزرق داكن"],
    inStock: true,
  },
  {
    id: 5,
    name: "حذاء New Balance 990v5",
    description: "حذاء جري متميز بتقنية ENCAP للدعم والراحة",
    price: 520,
    image: "/new-balance-990v5.png",
    brand: "New Balance",
    category: "أحذية رياضية",
    rating: 4.9,
    reviews: 203,
    sizes: ["40", "41", "42", "43", "44", "45", "46"],
    colors: ["رمادي", "أسود", "أزرق"],
    inStock: true,
  },
  {
    id: 6,
    name: "جاكيت Nike Tech Fleece",
    description: "جاكيت رياضي دافئ بتقنية Tech Fleece المبتكرة",
    price: 280,
    originalPrice: 350,
    image: "/nike-tech-fleece-jacket.png",
    brand: "Nike",
    category: "جاكيتات",
    rating: 4.8,
    reviews: 91,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["أسود", "رمادي", "أزرق داكن"],
    inStock: true,
  },
  {
    id: 7,
    name: "حقيبة Adidas Duffel",
    description: "حقيبة رياضية واسعة مثالية للصالة الرياضية والسفر",
    price: 180,
    image: "/adidas-duffel-bag.png",
    brand: "Adidas",
    category: "حقائب رياضية",
    rating: 4.4,
    reviews: 78,
    sizes: ["متوسط", "كبير"],
    colors: ["أسود", "أزرق", "أحمر"],
    inStock: true,
  },
  {
    id: 8,
    name: "بنطال Puma Training",
    description: "بنطال تدريب مرن ومريح للأنشطة الرياضية المختلفة",
    price: 160,
    originalPrice: 200,
    image: "/puma-training-pants.png",
    brand: "Puma",
    category: "بناطيل رياضية",
    rating: 4.6,
    reviews: 112,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["أسود", "رمادي", "أزرق داكن"],
    inStock: true,
  },
  {
    id: 9,
    name: "حذاء Jordan 1 Mid",
    description: "حذاء كرة سلة أيقوني بتصميم كلاسيكي من جوردان",
    price: 420,
    image: "/air-jordan-1-mid.png",
    brand: "Jordan",
    category: "أحذية رياضية",
    rating: 4.7,
    reviews: 189,
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["أسود وأحمر", "أبيض وأسود", "أزرق وأبيض"],
    inStock: true,
  },
  {
    id: 10,
    name: "تيشرت Reebok CrossFit",
    description: "تيشرت مخصص لتمارين CrossFit بقماش مقاوم للرطوبة",
    price: 85,
    originalPrice: 110,
    image: "/reebok-crossfit-shirt.png",
    brand: "Reebok",
    category: "تيشرتات",
    rating: 4.5,
    reviews: 64,
    sizes: ["S", "M", "L", "XL"],
    colors: ["أسود", "أبيض", "أحمر"],
    inStock: true,
  },
  {
    id: 11,
    name: "حذاء Converse Chuck Taylor",
    description: "حذاء كاجوال كلاسيكي بتصميم عتيق ومريح",
    price: 220,
    image: "/classic-converse.png",
    brand: "Converse",
    category: "أحذية رياضية",
    rating: 4.3,
    reviews: 145,
    sizes: ["38", "39", "40", "41", "42", "43", "44"],
    colors: ["أسود", "أبيض", "أحمر", "أزرق"],
    inStock: true,
  },
  {
    id: 12,
    name: "معدات تمرين Under Armour",
    description: "مجموعة معدات تمرين متكاملة للتدريب المنزلي",
    price: 350,
    originalPrice: 450,
    image: "/placeholder-whyvw.png",
    brand: "Under Armour",
    category: "معدات رياضية",
    rating: 4.6,
    reviews: 87,
    sizes: ["قياس واحد"],
    colors: ["أسود", "رمادي"],
    inStock: true,
  },
]
